stages:
  - build
  - push

default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

build:
  stage: build
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  # only:
  #   - tags
  rules:
    # - if: $CI_COMMIT_TAG && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"
  tags:
    - docker-builder
  before_script:
    - docker info
  script:
    - export ARTIFACT_NAME="$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - docker build -t ${ARTIFACT_NAME} .
    # - docker push ${ARTIFACT_NAME}
  artifacts:
    paths:
      - /var/lib/docker
    expire_in: 1h

push:
  stage: push
  tags:
    - docker-builder
  # only:
  #   - main
  #   - master
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
  script:
    - export ARTIFACT_NAME="$CI_PROJECT_NAME:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - docker push ${ARTIFACT_NAME} 
  dependencies:
    - build