stages:
  - build
  - push

default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

build:
  stage: build
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
      DOCKER_CLIENT_TIMEOUT: 300
      COMPOSE_HTTP_TIMEOUT: 300
  # only:
  #   - tags
  rules:
    # - if: $CI_COMMIT_TAG && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"
  tags:
    - docker-builder
  before_script:
    - ping -c 4 registry.liftedinit.org
    - curl -v https://registry.liftedinit.org:8443/v2/
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - export ARTIFACT_NAME="$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
    - docker build -t ${ARTIFACT_NAME} .
    - docker push  ${ARTIFACT_NAME}

# push:
#   stage: push
#   # only:
#   #   - main
#   #   - master
#   before_script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   script:
#     - export ARTIFACT_NAME="$CI_PROJECT_NAME:${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}"
#     - docker pull ${ARTIFACT_NAME}
#     - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
#     - docker push $DOCKER_REGISTRY/${ARTIFACT_NAME} 
#   dependencies:
#     - build 

